export enum AdminNotificationEvent {
  TEACHER_VERIFICATION = 'TEACHER_VERIFICATION',
  LOCATION_CHANGE_REQUEST = 'LOCATION_CHANGE_REQUEST',
  SUSPENSION_APPEAL = 'SUSPENSION_APPEAL',
  POST_REPORT = 'POST_REPORT',
  SUPPORT_REQUEST = 'SUPPORT_REQUEST',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  PAYOUT_ISSUE = 'PAYOUT_ISSUE',
  LIVE_SESSION_ISSUE = 'LIVE_SESSION_ISSUE',
  SYSTEM = 'SYSTEM',
  COMMUNITY_FLAGGED = 'COMMUNITY_FLAGGED',
  TEACHER_FLAGGED = 'TEACHER_FLAGGED',
  CONTENT_MODERATION = 'CONTENT_MODERATION',
}
